---
services: docker

env:
  - distro: centos7

before_install:
  # Pull container
  - 'docker pull geerlingguy/docker-$distro-ansible:latest'
  #- 'docker pull geerlingguy/docker-centos7-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-{distro}-ansible:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test Python3 availability

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/