---
- name: Check for built {{ compiled_python_dist_name }}
  command: python{{ compiled_python_version.rsplit('.', 1)[0] }} --version
  register: existing_python
  changed_when: false
  ignore_errors: True

- name: Build latest {{ compiled_python_dist_name }}
  block:

  - name: Freshen cache
    raw: sudo apt-get update
    register: task_result
    changed_when: False
    until: task_result.rc == 0
    retries: 5
    ignore_errors: yes

  - name: install deps for building {{ compiled_python_dist_name }}
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ compiled_python3_debian_deps }}"

  - name: Ensure unpack dir exists
    # target directory needs to exist to keep unarchive happy
    file:
      state: directory
      path: "{{ compiled_python_build_dir }}/{{ compiled_python_dist_name }}"

  - name: extract tarball
    unarchive:
      remote_src: True
      src: "https://www.python.org/ftp/python/{{ compiled_python_version }}/{{ compiled_python_tarball }}"
      dest: "{{ compiled_python_build_dir }}"

  - name: cfg build env
    command: ./configure {{ compiled_configure_flags }}
    args:
      chdir: "{{ compiled_python_build_dir }}/{{ compiled_python_dist_name }}"
    register: result
    changed_when: false

  - debug: msg="{{ result }}"
    when: result is failed

  - name: build new src
    make:
      chdir: "{{ compiled_python_build_dir }}/{{ compiled_python_dist_name }}"
      target: altinstall

  - name: clean up build of {{ compiled_python_dist_name }}
    file:
      state: absent
      path: "{{ compiled_python_build_dir }}/{{ compiled_python_dist_name }}"
    when: "compiled_python_cleanup"

  when: existing_python is failed

- name: testing for existing build of {{ compiled_python_dist_name }}
  command: python{{ compiled_python_version.rsplit('.', 1)[0] }} --version
  register: existing_python
  changed_when: false

- debug: msg="{{ existing_python }} is present"